baseURL = "https://sendev-gmbh.onrender.com/"
languageCode = "en-us"
title = "SenDev GmbH"
theme = "minos"

[menu]
	
	[[menu.main]]
		identifier = "about"
		name = "About"
		url = "/content/"
		weight = 1
